### ISSUE TITLE
Should the current SNAPSHOT version of Hygieia core be 3.5.9-SNAPSHOT 

### ISSUE THREAD

**Issue by shishirchaturvedi** [Hygieia/hygieia-core#189]
I see that the latest release version of Hygieia is [3.5.8](https://search.maven.org/artifact/com.capitalone.dashboard/core/3.5.8/jar). Considering that the current SNAPSHOT version for core should be 3.5.9-SNAPSHOT. I am curious why the current SNAPSHOT version of this project (hygieia-core) is 3.5.8-SNAPSHOT.

Reference -
[During the release process, a version of x.y-SNAPSHOT changes to x.y. The release process also increments the development version to x.(y+1)-SNAPSHOT. For example, version 1.0-SNAPSHOT is released as version 1.0, and the new development version is version 1.1-SNAPSHOT.](http://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version
)

**Comment by rvema** [comment]
#188 should have taken care of this

**Comment by shishirchaturvedi** [comment]
@rvema Nice.Thank you!

**Comment by rvema** [comment]
You are welcome, working on implementing the maven release process on this project. If you have any valuable suggestions in this regard please do share we can incorporate the same
