### ISSUE TITLE
Maven build failing for version 3.6.8

### ISSUE THREAD

**Issue by vogelrh** [Hygieia/hygieia-core#217]
**Affects:** Version 3.6.8>.
While performing a fresh installation of Hygieia on my Mac, the Maven build of hygiea-core fails with the following message:

![image](https://user-images.githubusercontent.com/9013105/79996958-0a828a00-8487-11ea-87df-2176b97dc98c.png)

When I revert back to version 3.6.7 the build was successful.

**Comment by rvema** [comment]
when was the last time your tried this? There was an issue with Maven Central yesterday and we don't see that issue this morning

**Comment by vogelrh** [comment]
I tried it this morning ~ 11 EST

**Comment by rvema** [comment]
That's odd, the master branch with 3.6.9-SNAPSHOT is compiling well. https://github.com/Hygieia/hygieia-core/runs/610010752?check_suite_focus=true

**Comment by rvema** [comment]
Alternatively can you try 3.6.9 version?

**Comment by vogelrh** [comment]
Resolved the issue. I deleted my local Maven cache, cleaned out my local Hygieia directory,  disconnected from my corporate network (vpn connection) and started the install process over.
It worked fine.
