### ISSUE TITLE
commit - 378c97c993588971efbbaee387b70de84a3c2c0d

### ISSUE THREAD

**Issue by VivekBuzruk** [hygieia/hygieia-core#293]
**Affects:** \<hygieia-core-version-number>.

---

Check diff for above commit -> https://github.com/Hygieia/hygieia-core/commit/378c97c993588971efbbaee387b70de84a3c2c0d#diff-78720a6741a87da7354434f03814ec4c4cbf5ac4f3d1932e5db38f348d13d3dc

Where is "CollectorType.Product" is associated with the component of team dashboard? unable to understand changes in "processBuild and processFailedBuild where one tries to fetch Product collector for a component of Team application.
`
            List<CollectorItem> productCIs = component.getCollectorItems(CollectorType.Product);      
            for(CollectorItem productCI : productCIs) {
`
Earlier code appeared to be correct, as pipelines are associated with Team Dashboards.

Appreciate your guidance.

**Comment by rvema** [comment]
@chzhanpeng Can you respond back?

**Comment by VivekBuzruk** [comment]
I found that CommitEventListener require additional changes to address the issue of commits to be seen as part of Pipeline stages.  Will await for response.

Thanks

**Comment by rvema** [comment]
@VivekBuzruk please propose the changes needed through a PR and We can get that reviewed and merged.

**Comment by VivekBuzruk** [comment]
Check attached Patch file 

[0002-Restore-the-behavior-of-adding-COMMIT-and-BUILD-stag.zip](https://github.com/Hygieia/hygieia-core/files/5786828/0002-Restore-the-behavior-of-adding-COMMIT-and-BUILD-stag.zip)
