### ISSUE TITLE
Not able to build in Windows 10

### ISSUE THREAD

**Issue by kamal-brill** [Hygieia/hygieia-core#37]
Hi all,
I couldn't able to build the `hygieia-core` project in Windows 10.

## Steps to Reproduce:

1. Clone the [repo](https://github.com/Hygieia/hygieia-core)
2. Open Command prompt/Power Shell
3. Navigate to the cloned repo
4. Run `mvn clean install package`

## Expected:
Build to be successfull

## Actual:

![hygieia-core build error](https://user-images.githubusercontent.com/46436784/51908496-0258ad80-23f0-11e9-8727-a2b40dc275db.png)

**Comment by rvema** [comment]
Can you post the version of maven and Java?

**Comment by kamal-brill** [comment]
**Maven:** 3.6.0
**Java:** jdk-11.0.2

**Comment by rvema** [comment]
We have not tried on jdk11 , can you try with jdk 10 or lower?

**Comment by D-M-Moriarty** [comment]
![image](https://user-images.githubusercontent.com/17987709/52233883-24eb3a80-28b8-11e9-8a7e-7ddf6e261351.png)
Im getting the same issue on mac

**Comment by D-M-Moriarty** [comment]
<dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>



Adding the following repositories fixed this issue for me

**Comment by stevegal** [comment]
split packages causing issues with the module system? Try jdk8

**Comment by D-M-Moriarty** [comment]
Added Dependencies that fixed it

**Comment by rvema** [comment]
@D-M-Moriarty Is it #43 to fix the build issues with JDK11?

**Comment by D-M-Moriarty** [comment]
no on JDK10

**Comment by rvema** [comment]
I will merge it then to make it compatible with JDK10

**Comment by rvema** [comment]
Can you confirm if this is still an issue?

**Comment by D-M-Moriarty** [comment]
No it's not an issue for me anymore

**Comment by rvema** [comment]
Thanks for confirming!
